export const FOCUS = 'focus_focused_true'
export const BLUR = 'blur_focused_false'
export const CHANGELIST = 'change_list'
export const MOUSE_ENTER = 'mouse_enter'
export const MOUSE_LEAVE = 'mouse_leave'
export const CHANGE_PAGE = 'change_page'